desktop: migrate from Sway to i3 on X11
Replace the Sway/Wayland setup with startx and i3, swap WezTerm for Alacritty, and update monitor, screenshot, clipboard, and notification tooling for X11.

Also add an i3 window switcher, configure libinput touchpad settings, pass unstable packages through flake args, and refresh nixpkgs-unstable.

diff --git a/home/files/bin/external-monitor-ls b/home/files/bin/external-monitor-ls
--- a/home/files/bin/external-monitor-ls
+++ b/home/files/bin/external-monitor-ls
@@ -21,9 +21,9 @@ if [[ -n "${1:-}" ]]; then
   exit 2
 fi
 
-if [[ -z "${SWAYSOCK:-}" ]]; then
-  echo "ERROR: SWAYSOCK is not set. Run this inside Sway." >&2
+if [[ -z "${DISPLAY:-}" ]]; then
+  echo "ERROR: DISPLAY is not set. Run this inside X11." >&2
   exit 1
 fi
 
-swaymsg -t get_outputs | jq -r '.[].name'
+xrandr --query | awk '$2 == "connected" { print $1 }'
diff --git a/home/files/bin/external-monitor-off b/home/files/bin/external-monitor-off
--- a/home/files/bin/external-monitor-off
+++ b/home/files/bin/external-monitor-off
@@ -21,13 +21,13 @@ if [[ -n "${1:-}" ]]; then
   exit 2
 fi
 
-if [[ -z "${SWAYSOCK:-}" ]]; then
-  echo "ERROR: SWAYSOCK is not set. Run this inside Sway." >&2
+if [[ -z "${DISPLAY:-}" ]]; then
+  echo "ERROR: DISPLAY is not set. Run this inside X11." >&2
   exit 1
 fi
 
 laptop_output="${EXTERNAL_MONITOR_LAPTOP_OUTPUT:-eDP-1}"
-mapfile -t connected_outputs < <(swaymsg -t get_outputs | jq -r '.[].name')
+mapfile -t connected_outputs < <(xrandr --query | awk '$2 == "connected" { print $1 }')
 
 laptop_connected=false
 for connected_output in "${connected_outputs[@]}"; do
@@ -52,9 +52,9 @@ if [[ "$laptop_connected" != true ]]; then
   exit 1
 fi
 
-swaymsg -q output "$laptop_output" enable
+xrandr --output "$laptop_output" --auto
 for connected_output in "${connected_outputs[@]}"; do
   if [[ "$connected_output" != "$laptop_output" ]]; then
-    swaymsg -q output "$connected_output" disable
+    xrandr --output "$connected_output" --off
   fi
 done
diff --git a/home/files/bin/external-monitor-use b/home/files/bin/external-monitor-use
--- a/home/files/bin/external-monitor-use
+++ b/home/files/bin/external-monitor-use
@@ -24,13 +24,13 @@ if [[ "$#" -ne 1 ]]; then
   exit 2
 fi
 
-if [[ -z "${SWAYSOCK:-}" ]]; then
-  echo "ERROR: SWAYSOCK is not set. Run this inside Sway." >&2
+if [[ -z "${DISPLAY:-}" ]]; then
+  echo "ERROR: DISPLAY is not set. Run this inside X11." >&2
   exit 1
 fi
 
 target_output="$1"
-mapfile -t connected_outputs < <(swaymsg -t get_outputs | jq -r '.[].name')
+mapfile -t connected_outputs < <(xrandr --query | awk '$2 == "connected" { print $1 }')
 
 target_connected=false
 for connected_output in "${connected_outputs[@]}"; do
@@ -46,9 +46,9 @@ if [[ "$target_connected" != true ]]; then
   exit 1
 fi
 
-swaymsg -q output "$target_output" enable
+xrandr --output "$target_output" --auto
 for connected_output in "${connected_outputs[@]}"; do
   if [[ "$connected_output" != "$target_output" ]]; then
-    swaymsg -q output "$connected_output" disable
+    xrandr --output "$connected_output" --off
   fi
 done
